
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.Random;
import java.util.concurrent.TimeUnit;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {

    public int time = 0;

    public int ArrayInt[];
    public String ArrayString[];
    public Citizen ArrayCitizen[];

    public LinkedList<Integer> LinkedListInt = new LinkedList<>();
    public LinkedList<String> LinkedListString = new LinkedList<>();
    public LinkedList<Citizen> LinkedListCitizen = new LinkedList<>();

    class CitizenComparator implements Comparator<Citizen> {

        @Override
        public int compare(Citizen p1, Citizen p2) {
            return p1.getId().compareTo(p2.getId());
        }
    }

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.setTitle("[เจ้ากรรม นายเวร]");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Title: Java Sorting Performance 07610XXX Ms.Grim Reaper");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("จำนวนข้อมูล");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("การจัดเก็บข้อมูล");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ชนิดของข้อมูล ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("เวลาที่ใช้");

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("100");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("1k");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("10k");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4.setText("100k");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton5.setText("Array");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton6.setText("LinkedList");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("int");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("String");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Citizen ");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("?? sec. ");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("?? sec. ");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("?? sec. ");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Gen-data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Sort-data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Gen-progress");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addGap(28, 28, 28)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton6)))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(15, 15, 15)
                        .addComponent(jButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean k100 = jRadioButton1.isSelected();
        boolean k1k = jRadioButton2.isSelected();
        boolean k10k = jRadioButton3.isSelected();
        boolean k100k = jRadioButton4.isSelected();
        boolean array = jRadioButton5.isSelected();
        boolean linkedlist = jRadioButton6.isSelected();
        if (array) {
            if (k100) {
                jProgressBar1.setMaximum(100);
                ArrayInt = new int[100];
                ArrayString = new String[100];
                ArrayCitizen = new Citizen[100];
                for (int i = 0; i < 100; i++) {
                    ArrayInt[i] = new Random().nextInt(9) + 1;
                    ArrayString[i] = Citizen.genRandomString(5, true);
                    ArrayCitizen[i] = new Citizen();
                    jProgressBar1.setValue(i);
                    jProgressBar1.update(jProgressBar1.getGraphics());
                }
            } else if (k1k) {
                jProgressBar1.setMaximum(1000);
                ArrayInt = new int[1000];
                ArrayString = new String[1000];
                ArrayCitizen = new Citizen[1000];
                int c = 0;
                //jProgressBar1.setIndeterminate(true);
                for (int i = 0; i < 1000; i++) {
                    ArrayInt[i] = new Random().nextInt(9) + 1;
                    ArrayString[i] = Citizen.genRandomString(5, true);
                    ArrayCitizen[i] = new Citizen();

                    jProgressBar1.setValue(i);
                    jProgressBar1.update(jProgressBar1.getGraphics());
                    //jProgressBar1.updateUI();
                }
            } else if (k10k) {
                jProgressBar1.setMaximum(10000);
                ArrayInt = new int[10000];
                ArrayString = new String[10000];
                ArrayCitizen = new Citizen[10000];
                for (int i = 0; i < 10000; i++) {
                    ArrayInt[i] = new Random().nextInt(9) + 1;
                    ArrayString[i] = Citizen.genRandomString(5, true);
                    ArrayCitizen[i] = new Citizen();
                    jProgressBar1.setValue(i);
                    jProgressBar1.update(jProgressBar1.getGraphics());
                }
            } else if (k100k) {
                jProgressBar1.setMaximum(100000);
                ArrayInt = new int[100000];
                ArrayString = new String[100000];
                ArrayCitizen = new Citizen[100000];
                for (int i = 0; i < 100000; i++) {
                    ArrayInt[i] = new Random().nextInt(9) + 1;
                    ArrayString[i] = Citizen.genRandomString(9, true);
                    ArrayCitizen[i] = new Citizen();
                    jProgressBar1.setValue(i);
                    jProgressBar1.update(jProgressBar1.getGraphics());
                }
            }
        } else if (linkedlist) {
            if (k100) {
                jProgressBar1.setMaximum(100);
                for (int i = 0; i < 100; i++) {
                    LinkedListInt.add(new Random().nextInt(9) + 1);
                    LinkedListString.add(Citizen.genRandomString(9, true));
                    LinkedListCitizen.add(new Citizen());
                    jProgressBar1.setValue(i);
                    jProgressBar1.update(jProgressBar1.getGraphics());
                }
            } else if (k1k) {
                jProgressBar1.setMaximum(1000);
                for (int i = 0; i < 1000; i++) {

                    LinkedListInt.add(new Random().nextInt(9) + 1);
                    LinkedListString.add(Citizen.genRandomString(9, true));
                    LinkedListCitizen.add(new Citizen());
                    jProgressBar1.setValue(i);
                    jProgressBar1.update(jProgressBar1.getGraphics());
                }
            } else if (k10k) {
                jProgressBar1.setMaximum(10000);
                for (int i = 0; i < 10000; i++) {
                    LinkedListInt.add(new Random().nextInt(9) + 1);
                    LinkedListString.add(Citizen.genRandomString(9, true));
                    LinkedListCitizen.add(new Citizen());
                    jProgressBar1.setValue(i);
                    jProgressBar1.update(jProgressBar1.getGraphics());
                }
            } else if (k100k) {
                jProgressBar1.setMaximum(100000);
                for (int i = 0; i < 100000; i++) {
                    LinkedListInt.add(new Random().nextInt(9) + 1);
                    LinkedListString.add(Citizen.genRandomString(9, true));
                    LinkedListCitizen.add(new Citizen());
                    jProgressBar1.setValue(i);
                    jProgressBar1.update(jProgressBar1.getGraphics());
                }
            }

        }
//        if (k100 || k1k) {
//            jButton2.doClick();
//        }

        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton5.isSelected()) {
            double timeArrayint = 0;
            for (int i = 0; i < 3; i++) {
                long start = System.nanoTime();
                Arrays.sort(ArrayInt);
                long finish = System.nanoTime();
                long timeElapsed = finish - start;

                System.out.format("Milli = %s, ( S_Start : %s, S_End : %s ) \n", timeElapsed, start, finish);
//        System.out.println("ArrayInt" + timeElapsed * 0.0000000001); //divide by 1000000 to get milliseconds. 1 mill = 0.001 sec. *0.000001*0.001
                double t = timeElapsed * 0.0000000001;
                System.out.println(t);
                String tt = Double.toString(t);
                timeArrayint += t;
                System.out.println("Int tt " + tt);
                String ttt = (String) tt.substring(0, 4);
                System.out.println(ttt);
                jTextField1.setText(ttt);
//        System.out.println(Citizen.millisToShortDHMS((long) (timeElapsed * 0.000001)));
            }
            timeArrayint = timeArrayint / 3;
            jTextField1.setText((Double.toString(timeArrayint)).substring(0, 4));

            timeArrayint = 0;
            for (int i = 0; i < 3; i++) {
                long startString = System.nanoTime();
                Arrays.sort(ArrayString);
                long finishString = System.nanoTime();
                long timeElapsedString = finishString - startString;
                double t = timeElapsedString * 0.0000000001;
                System.out.format("Milli = %s, ( S_Start : %s, S_End : %s ) \n", timeElapsedString, startString, finishString);
                System.out.println(t);
                timeArrayint += t;
                String tString = Double.toString(t);
                System.out.println("String tt " + tString);
                String ttString = (String) tString.substring(0, 4);
                System.out.println(ttString);
                jTextField2.setText(ttString);
            }
            timeArrayint = timeArrayint / 3;
            jTextField2.setText((Double.toString(timeArrayint)).substring(0, 4));

            timeArrayint = 0;
            for (int i = 0; i < 3; i++) {
                long start = System.nanoTime();
                Arrays.sort(ArrayCitizen, new CitizenComparator());
                long finish = System.nanoTime();
                long timeElapsed = finish - start;
                double t = timeElapsed * 0.0000000001;
                System.out.format("Milli = %s, ( S_Start : %s, S_End : %s ) \n", timeElapsed, start, finish);
                System.out.println(t);
                timeArrayint += t;
                String tCitizen = Double.toString(t);
                System.out.println("Citizentt " + tCitizen);
                String ttCitizen = (String) tCitizen.substring(0, 4);
                System.out.println(ttCitizen);
                jTextField3.setText(ttCitizen);
            }
            timeArrayint = timeArrayint / 3;
            jTextField3.setText((Double.toString(timeArrayint)).substring(0, 4));
        }

        if (jRadioButton6.isSelected()) {
            long start = System.nanoTime();
            Collections.sort(LinkedListInt);
            long finish = System.nanoTime();
            long timeElapsed = finish - start;

            System.out.format("Milli = %s, ( S_Start : %s, S_End : %s ) \n", timeElapsed, start, finish);
//        System.out.println("ArrayInt" + timeElapsed * 0.0000000001); //divide by 1000000 to get milliseconds. 1 mill = 0.001 sec. *0.000001*0.001
            double t = timeElapsed * 0.0000000001;
            System.out.println(t);
            String tt = Double.toString(t);
            System.out.println("Int tt " + tt);
            String ttt = (String) tt.substring(0, 4);
            System.out.println(ttt);
            jTextField1.setText(ttt);
//        System.out.println(Citizen.millisToShortDHMS((long) (timeElapsed * 0.000001)));

            start = System.nanoTime();
            Collections.sort(LinkedListString);
            finish = System.nanoTime();
            timeElapsed = finish - start;
            System.out.format("Milli = %s, ( S_Start : %s, S_End : %s ) \n", timeElapsed, start, finish);
            t = timeElapsed * 0.0000000001;
            System.out.println(t);
            String tString = Double.toString(t);
            System.out.println("String tt " + tString);
            String ttString = (String) tString.substring(0, 4);
            System.out.println(ttString);
            jTextField2.setText(ttString);

            start = System.nanoTime();
            Collections.sort(LinkedListCitizen, new CitizenComparator());
            finish = System.nanoTime();
            timeElapsed = finish - start;
            System.out.format("Milli = %s, ( S_Start : %s, S_End : %s ) \n", timeElapsed, start, finish);
            t = timeElapsed * 0.0000000001;
            System.out.println(t);
            String tCitizen = Double.toString(t);
            System.out.println("Citizentt " + tCitizen);
            String ttCitizen = (String) tCitizen.substring(0, 4);
            System.out.println(ttCitizen);
            jTextField3.setText(ttCitizen);
        }

        jTextField1.setText(jTextField1.getText()+" sec.");
        jTextField2.setText(jTextField2.getText()+" sec.");
        jTextField3.setText(jTextField3.getText()+" sec.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
//        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
//        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
//        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
//        jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
//       jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        jRadioButton5.setSelected(false);
//        jRadioButton6.setSelected(false);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static String allname[], alladdress[], alloccupation[];

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        allname = Citizen.readFile("passengerNames.txt");
        alladdress = Citizen.readFile("address.txt");
        alloccupation = Citizen.readFile("gistfile1.txt");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
