
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
class test implements Serializable {//สร้างคลาสตามที่โจทย์กำหนดคือ มีฟิลด์อย่างน้อย 4 ฟิลด์

    int number;
    String name;
    int age;
    int Height;
    int Weight;

    public test(int number, String name, int age, int Height, int Weight) {
        this.number = number;
        this.name = name;
        this.age = age;
        this.Height = Height;
        this.Weight = Weight;
    }

    public String toString() {//return เป็น String คั่นฟิลด์ต่างๆด้วย "," 
        return number + "," + name + "," + age + "," + Height + "," + Weight;
    }
}

public class test1_JFrame extends javax.swing.JFrame {

    /*
    อันนี้คือการใช้ array แบบง่ายๆถึกๆตรงๆ แล้วยังเป็น static ทำไมนะหรอเพื่อให้ง่ายต่อการเรียกใช้
    ทำให้ array ที่เป็น static เนี่ยเป็น array ใจง่ายเรียกใช้จากที่ใดก็ได้ 
     */
    public static test[] data;
    public static test[] temp;
    public static String[] header = {"Number", "Name", "Age", "Height", "Weight"};//ชื่อหัว column ในตารางของเรา
    //public static String[] sex = {"male","Female"};
    public static boolean s = false; //ใช้เพื่อบอกว่ามีการแก้ไขข้อมูลใน row ไหนหรือเปล่า

    /**
     * Creates new form test1_JFrame
     */
    public test1_JFrame() {
        initComponents();
        this.setTitle( "เจ้ากรรม นายเวร" );
        jTextField1.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jgen = new javax.swing.JButton();
        jSave = new javax.swing.JButton();
        jload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Title: Object Editor");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jgen.setText("Generate");
        jgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgenActionPerformed(evt);
            }
        });

        jSave.setText("Save");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jload.setText("load");
        jload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jgen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jload, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jgen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jload, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgenActionPerformed
        // TODO add your handling code here:
        Random r = new Random();//คงคุ้นๆกันแล้วกันอันนี้ใช้ตลอดใช้บ่อย random สุ่มๆ 
        int n = 100; //จำนวนที่ต้องการสร้างวัตถุอัตโนมัติตามโจทย์กำหนด
        // Generate
        data = new test[n];// new array ที่เราประกาศด้วย static แบบใจง่ายด้วยขนาดที่ต้องการ 
        for (int i = 0; i < n; i++) {// วนลูปแบบ ไม่มูฟออน 100 รอบ
            int number = i + 1;//ลำดับ
            String name = genRandomString(r.nextInt(5) + 5);//ชื่อที่สุ่มมาจาก method สุ่ม String
            int HEIGHT = r.nextInt(100) + 100; //ส่วนสูงที่สุ่มแต่ให้มีค่าเริ่มต้นที่ 100
            int age = r.nextInt(30) + 1;//อายุซึ่งก๋สุ่มเช่นเคยสุ่มตั้งแต่ 1-30
            int Weight = r.nextInt(100) + 40;//น้ำหนักก็สุ่มเช่นเคยแต่ให้มีค่าต่ำสุดที่ 40 
            data[i] = new test(number, name, age, HEIGHT, Weight); //สร้างวัตถุพร้อมยัดใส่เข้าไปใน array ใจง่ายของเราแบบหวานๆ
        }

        temp = Arrays.copyOf(data, n);//อันนี้ไม่ต้องมีก็ได้ แต่ใส่ไว้ในกรณีที่อยากจะมี gen เพิ่มรวมกับของเก่าหรือใดๆแนวๆนั้น

        //-->>> ส่วนของการเอาขึ้นตารางซึ่งเห็นเหมือนๆกันแทบทุกอันนะ
        Object[][] x = new Object[n][];//สร้าง array 2D เสมือนตาราง

        for (int i = 0; i < n; i++) {
            x[i] = data[i].toString().split(",");//ใส่ข้อมูลลงไปใน row ตามจำนวนที่กำหนดไว้
        }

        javax.swing.table.DefaultTableModel model1 = new javax.swing.table.DefaultTableModel(x, header);//ใส่ใน jtable (ข้อมูลแต่ละrowและcolumn,ชื่อ column)
        jTable1.setModel(model1);//แสดงขึ้น jtable ที่อยู่ใน GUI
        //<<<---ส่วนของการเอาขึ้นตาราง
    }//GEN-LAST:event_jgenActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed

        //--->>> อันจะเกิดขึ้นเมื่อมีการแก้ไขข้อความใน jTextField1
        if (jTextField1.getText() != "" && jTextField1 != null && s) {
            String[] split = jTextField1.getText().split(","); //นำข้อความมาเปลี่ยเป็น array โดยตัดด้วย ","
            int index = Integer.parseInt(split[0]) - 1;//หาว่ามาจาก index หรือ row ที่เท่าไร (-1 เพราะ เริ่มที่ 0)
            System.out.println(data[index]);//print มาเช็คดูเฉยๆ
            data[index] = new test(Integer.parseInt(split[0]), split[1], Integer.parseInt(split[2]), Integer.parseInt(split[3]), Integer.parseInt(split[4]));
            //ตรงนี้คือเอาข้อมูลที่ get มาจาก jTextField1 ที่แบ่งอยู่ใน array split แล้วมาสร้างเป็นวัตถุใหม่แทนที่ของเก่าที่อยู่ใน index ที่เราแก้ไขใน jTextField1
            jTextField1.setText(null);//เสร็จแล้วก็ set เป็น null
        }
        //<<<---

        //--->>> save ออกมาเป็น .ser จะได้ไฟล์ภาษาแปลกๆ ไปเปิดดูได้
        if (data != null) {//if(ต้องมีข้อมูลนะ ถึงจะ save)
            try {
                FileOutputStream fos = new FileOutputStream("data.ser");//ใน "ชื่อไฟล์.ser" เปลี่ยนตามโจทย์เลย
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(data);//ใส่ข้อมูลที่ต้องการ save 
                oos.close();
                fos.close();
                //ปิดฟังก์ชั่นที่ใช้ในการ save
                /* JOptionPane.showMessageDialog(this,
                        "Successfully saved data (" + data.length + " records) to 'Data.ser'",
                        "Info",
                        JOptionPane.INFORMATION_MESSAGE);*/
            } catch (Exception e) {//ถ้า save ไม่ได้ด้วยประการทั้งปวงไม่ว่าสาเหตุใดๆก็ตามจะทำคำสั่งใน catch
                System.out.println(e);//print error มาดู
                //>>>ทำให้มัหน้าต่างแจ้งว่า error อะไร 
                JOptionPane.showMessageDialog(this,
                        e,
                        "Error",
                        JOptionPane.WARNING_MESSAGE);
                //<<<
            }
        } else {/*จะแสดงข้อความ 
                    "Please press the 'Generate' button first"
                    "No data"
                   ว่าให้ใส่กดปุ่ม Gen เพื่อให้มี data
             */
            JOptionPane.showMessageDialog(this,
                    "Please press the 'Generate' button first",
                    "No data",
                    JOptionPane.WARNING_MESSAGE);
        }
        //<<<---
    }//GEN-LAST:event_jSaveActionPerformed

    private void jloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloadActionPerformed
        // TODO add your handling code here:

        try {//การ load 
            FileInputStream fis = new FileInputStream("data.ser");//ชื่อไฟล์ที่เดียวกับที่ save 
            ObjectInputStream ois = new ObjectInputStream(fis);
            data = (test[]) ois.readObject();// cacth ด้วย type ของ class ที่ save
            temp = Arrays.copyOf(data, data.length);//เป็นการ copy array data1 ใส่ array temp ที่มีขนาดเท่ากันมีข้อมูลเหมือนกัน
            ois.close();
            fis.close();
            //ปิดฟังก์ชั่นที่ใช้ในการ load

            /*JOptionPane.showMessageDialog(this,
                    "Successfully load data (" + temp.length + " records) from 'Data.ser'",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);*/
            //-->>> ส่วนของการเอาขึ้นตารางซึ่งเห็นเหมือนๆกันแทบทุกอันนะ
            Object[][] x = new Object[temp.length][];//สร้าง array 2D เสมือนตาราง

            for (int i = 0; i < temp.length; i++) {
                x[i] = temp[i].toString().split(",");//ใส่ข้อมูลลงไปใน row ตามจำนวนที่กำหนดไว้
            }

            javax.swing.table.DefaultTableModel model1 = new javax.swing.table.DefaultTableModel(x, header);//ใส่ใน jtable (ข้อมูลแต่ละrowและcolumn,ชื่อ column)
            jTable1.setModel(model1);//แสดงขึ้น jtable ที่อยู่ใน GUI
            //jLabel2.setText(Integer.toString(x.length) + " records");
            s = false;//ไม่ให้มีการแก้ไข row ปิดไว้ก่อน
            //<<<---ส่วนของการเอาขึ้นตาราง
        } catch (Exception e) {//ถ้าเกิด error ขึ้นมามันจะแสดงหน้าต่างว่า error อะไรในหน้าต่างใหม่
            JOptionPane.showMessageDialog(this,
                    e,
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jloadActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MouseEntered

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        /*jTable1MouseClicked เป็นเรื่องใหม่พอสมควร
        เป็นการทำงานเมื่อ คลิ๊ก ใน row ของ jtable
         */
        int index = jTable1.getSelectedRow();// return ค่า row ที่ถูกคลิ๊ก
        TableModel model = jTable1.getModel();// สร้างตัวเปรเป็นตัวแทนตารางในหน้า Gui
        int v1 = Integer.parseInt(model.getValueAt(index, 0).toString()); //ค่าใน column แรก คือ ลำดับมีค่าเป็น int แต่ get ออกมาเป็น String จึงใช้ Integer.parseInt ในการแปลง String >>> int
        String v2 = model.getValueAt(index, 1).toString(); //ค่าใน column ที่ 2 return เป็น String จาก method toString();
        String v3 = model.getValueAt(index, 2).toString();//ค่าใน column ที่ 3 return เป็น String จาก method toString();
        int v4 = Integer.parseInt(model.getValueAt(index, 3).toString());//ค่าใน column แรก คือ ลำดับมีค่าเป็น int แต่ get ออกมาเป็น String จึงใช้ Integer.parseInt ในการแปลง String >>> int
        String v5 = model.getValueAt(index, 4).toString();//ค่าใน column ที่ 5 return เป็น String จาก method toString();
        //System.out.println(v1+","+v2+","+v3+","+v4);
        jTextField1.setText(v1 + "," + v2 + "," + v3 + "," + v4 + "," + v5);
        //จากนั่นนำค่ามา set ใส่ jTextField1 ตามรูปแบบที่มักเขียนใน toString คั่นด้วย "," 
        s = true;//เปลี่ยนค่า s = true เพื่อบอก ฮั่นแหน่มีการแก้ไขบาง row นะ
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    //copy ไปใช้ได้เลยนะถ้ามีข้อที่แบบอะไรๆก็สุ่มชื่ออ่ะ 555
    public static String genRandomString(int n) {//method ที่ใช้ในการสุ่ม String (ความยาวของ String)
        Random random = new Random();
        String str = "";
        char[] letters = "abcdefghijklmnopqrstuvwxyz".toCharArray();//นำตัวอักษรมาแปลงใส่  array แบบถึกๆ
        for (int i = 0; i < n; i++) {//วนตามความยาวของ String ที่ต้องการ (ค่า n)
            str += letters[random.nextInt(26)];//สุ่มตัวอักษรมาต่อกันผ่านการเรียกจาก index ของ array letters ที่เก็บตัวอักษร
            if (i == 0) {
                str = str.toUpperCase();//ทำให้ตัวแรกของ String เป็นตัวพิมพ์ใหญ่
            }
        }
        return str;
    }

    //copy ไปใช้ได้เลยในกรณีสุ่มตัวเลข
    public static String genRandomInt(int n) {
        Random random = new Random();
        String str = "";
        char[] letters = "0123456789".toCharArray();//นำตัวเลขที่เป็น String มาแปลงใส่  array แบบถึกๆ
        for (int i = 0; i < n; i++) {//วนตามความยาวของ String ที่ต้องการ (ค่า n)
            str += letters[random.nextInt(10)];//สุ่มตัวอักษรที่เป็นตัวเลขมาต่อกันผ่านการเรียกจาก index ของ array letters ที่เก็บตัวอักษร
        }
        return str;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test1_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test1_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test1_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test1_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new test1_JFrame().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jgen;
    private javax.swing.JButton jload;
    // End of variables declaration//GEN-END:variables
}
